### ISSUE TITLE
E689: Can only index a List or Dictionary

### ISSUE THREAD

**Issue by archseer** [lambdalisue/gina.vim#66] opened 2017-03-20 17:02 UTC
"gina://my_project:status" [Read errors] --No lines in buffer--
Error detected while processing function <SNR>155_BufReadCmd[9]..gina#process#open[5]..<SNR>112_build_raw_args[9]..gina#core#askpass#wrap[2]..<SNR>131_askpass[1]..gina#core#repo#config[13]..<SNR>122_exten
d_config:
line   12:
E689: Can only index a List or Dictionary

**Comment by archseer** [comment] 2017-03-20 17:04
(This is on neovim 0.1.7)

**Comment by lambdalisue** [comment] 2017-03-21 02:04
It seems a bug but in case, could vou write reproduce steps?

**Comment by archseer** [comment] 2017-03-21 02:05
Happens on any `:Gina` command, I can't use the plugin at all -- was migrating from `vim-gita` which seems to work fine

**Comment by lambdalisue** [comment] 2017-03-21 02:10
For now, set something to git config may solve the issue.

**Comment by lambdalisue** [comment] 2017-03-21 02:12
And which os do you use?

**Comment by lambdalisue** [comment] 2017-03-21 02:43
I checked the code but could not find a problem. could you paste a result of git config --list ?

**Comment by lambdalisue** [comment] 2017-03-21 03:11
I think I got the reason. Could you try #67 ?

**Comment by lambdalisue** [comment] 2017-03-21 03:16
Note, in case, I would like to know your git config --list

**Comment by archseer** [comment] 2017-03-21 05:00
#67 solves it for me! my git config is available here https://github.com/archSeer/dotfiles/blob/master/gitconfig

**Comment by lambdalisue** [comment] 2017-03-21 09:04
Merged. Thanks 👍

**Closed as completed** 2017-03-21 09:04 UTC
Labels: bug
