### ISSUE TITLE
Use floating windows to show message 

### ISSUE THREAD

**Issue by wsdjeg** [lambdalisue/gina.vim#200] opened 2019-04-02 05:02 UTC
neovim has implemented floating windows feature. how about using it instead of put message into cmdline.

**Comment by lambdalisue** [comment] 2019-04-02 07:41
Show **which** messages?

**Comment by wsdjeg** [comment] 2019-04-02 11:12
result of gina command. such as `Gina add .` `Gina push`

**Comment by wsdjeg** [comment] 2019-04-02 11:12
btw. we can also use timer to close the message windows.

**Comment by lambdalisue** [comment] 2019-04-03 02:01
Ah, so like ASCII growl window for **notification** right? Interesting... Do you know example codes for flating windows? or PR is very welcome 👍

**Comment by wsdjeg** [comment] 2019-04-03 03:36
OK, I will have a try this weekend.

**Comment by wsdjeg** [comment] 2019-04-05 04:57
Just reading the code of gina, but failed to find out where does the message been printed out.

**Comment by lambdalisue** [comment] 2019-04-05 13:59
https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/command/_raw.vim#L43

**Comment by wsdjeg** [comment] 2019-04-26 15:11
hmm, I am sorry, but how about add an option to gina? so people can use this option to change default handle function?

**Comment by lambdalisue** [comment] 2019-04-30 16:14
> hmm, I am sorry, but how about add an option to gina? so people can use this option to change default handle function?

Sorry, I don't get what you need to know. What is your ideal image of usage?

**Comment by Kraust** [comment] 2019-07-05 23:43
I think that the original poster wanted a floating window created by `nvim_open_win()` as a valid opener type.

**Comment by resolritter** [comment] 2019-08-19 10:28
Hmm... Floating windows don't go away after you press enter, unlike multiline output to the command-line. You'd have to create a new hotkey just for closing it or expire them with a timer, but the latter is a bit weird (What if you want to keep seeing it? Do you need yet another hotkey for cancelling the timer?).

I'd be curious to know what pain motivated this idea.

**Comment by wsdjeg** [comment] 2019-08-20 07:45
you can just add a mapping to open a floating windows to show the message history of gina. this windows should be able to closed by mouse click.

**Comment by resolritter** [comment] 2019-08-20 13:05
@wsdjeg is your ideal of usage like this?

- Gina no longer echoes the git commands' outputs to the command line. It will output to a separate buffer.
- You can press a hotkey to toggle the buffer as a floating window.

I think something like that would be very cool, although it would also need extra hotkeys for scrolling and clearing the buffer.

**Comment by joefiorini** [comment] 2019-10-04 13:30
I love the idea of timer-based notification messages in Vim. Sounds like that could make a good plugin on its own, haha.

One thought though, the log of messages could get long enough throughout the day that interacting with it in a floating window gets unwieldy. What about having a simple command to open the message log in a standard window (maybe with a —opener like other Gina commands). I’ve seen other plugins do this for logs and it works fine.

**Comment by wsdjeg** [comment] 2019-10-04 13:38
@resolritter yeah, use (a) simple buffer on the topright to show the message. maybe more than one buffer.

**Comment by wsdjeg** [comment] 2019-10-04 14:01
here is my example plugin, and of cause it based on SpaceVim API.

https://github.com/wsdjeg/DotFiles/blob/master/SpaceVim.d/plugin/notification.vim

![notifications](https://user-images.githubusercontent.com/13142418/66218434-c5218980-e6fb-11e9-805a-4bbe7addc6d4.gif)

**Comment by resolritter** [comment] 2019-10-04 19:32
Floating windows are amazing!

I think this idea of keeping an internal log with the previous' commands outputs can be useful. If that's made possible, then the floating window functionality can even be implemented as a separate plugin if the author wishes.

What does @lambdalisue think of this? Is it worthwhile do add machinery to record (and publish) the stdout/stderr of every command used internally by Gina? Or do you don't think the possibilities of usage are useful?

**Comment by lambdalisue** [comment] 2019-10-05 10:05
While Gina executes commands asynchronously, I think using a floating window is a good idea.
But the problem is that the API in Vim and Nevoim for the floating window/popup window is quite different. That's why **"I"** could not be bothered to implement such a feature by myself. I'd love to see PRs 👍

**Closed as completed** 2020-02-09 23:45 UTC
Labels: enhancement, need response
