### ISSUE TITLE
Failed to run Gina commit in windows

### ISSUE THREAD

**Issue by wsdjeg** [lambdalisue/gina.vim#232] opened 2019-11-16 04:18 UTC
I use this plugin in windows, and when I run `:Gina commit` I got:

```
[gina] Fail: git --no-pager -c core.editor=false -c color.status=always -C C:\Users\wsdjeg\.SpaceVim commit --edit
[gina] error: There was a problem with the editor 'false'.
[gina] Please supply the message using either -m or -F option.

```

**Comment by K1DV5** [comment] 2019-11-16 09:44
Seems a duplicate of #229

**Closed as completed** 2019-11-16 11:08 UTC
